# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0da3c57e2a9240b45411dc5330731bbbb443cb706f20ac83d964857e4e7b211229ee342fcbeb8ab4d260083508b172560aefbff5bce6ae5df4c38c06e9e2b593

test:
  secret_key_base: b59f3787f8054a1acf615b6ddb8c08accdbb1cdffa367dfe4e209dd7867d89a844534b260aee5fcfafe0e2fd2ddb8c578a5cd71793e15d70f4f17d34f1232382

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
